#- name: Set Hostname
#  ansible.builtin.shell: set-hostname frontend

- name: Install NGINX
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy NGINX conf
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Clean Old content
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download & Extract Frontend Content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Restart NGINX Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Create Nginx Prometheus Exporter Directory
  ansible.builtin.file:
    path: /opt/nginx_exporter
    state: directory

- name: Downlaod Nginx Prometheus Exporter
  ansible.builtin.unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
    dest: /opt/nginx_exporter
    remote_src: yes

- name: Copy Nginx Prometheus Exporter Service
  ansible.builtin.copy:
    src: nginx-exporter.service
    dest: /etc/systemd/system/nginx_exporter.service

- name: Restart NGINX Prometheus Exporter Service
  ansible.builtin.systemd:
    name: nginx_exporter
    state: restarted
    enabled: yes
