- name: Set Hostname
  ansible.builtin.shell: set-hostname {{ component }}

- name: Start {{component}} Service
  ansible.builtin.systemd:
    name: "{{component}}"
    state: restarted
    enabled: yes
    daemon_reload: yes