- name: Start {{component}} Service
  ansible.builtin.systemd:
    name: "{{component}}"
    state: restarted
    enabled: yes
    daemon_reload: yes

## Rsyslog Config
- name: Setup Rsyslog config file
  ansible.builtin.template:
    src: "rsyslog.conf"
    dest: /etc/rsyslog.d/expense.conf

- name: Restart Rsyslog Service
  ansible.builtin.systemd:
    name: "rsyslog"
    state: restarted
